// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIptkDEBQBSgyOBkeVoMe2TxR62cnLv0Y',
    appId: '1:511465971647:web:884cbce9e8ac0faf6c0b0a',
    messagingSenderId: '511465971647',
    projectId: 'solara-29b37',
    authDomain: 'solara-29b37.firebaseapp.com',
    storageBucket: 'solara-29b37.firebasestorage.app',
    measurementId: 'G-FJ2HGCWN9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5ePS4EuLcpnVqrUxRu8o9RNElwO_1j9s',
    appId: '1:511465971647:android:c56940d9799a7f366c0b0a',
    messagingSenderId: '511465971647',
    projectId: 'solara-29b37',
    storageBucket: 'solara-29b37.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCy8ZEhwaM99gdgT_c7n77W6sYFMcXNaf0',
    appId: '1:511465971647:ios:bc6aa6e765335c836c0b0a',
    messagingSenderId: '511465971647',
    projectId: 'solara-29b37',
    storageBucket: 'solara-29b37.firebasestorage.app',
    iosBundleId: 'com.example.solara',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCy8ZEhwaM99gdgT_c7n77W6sYFMcXNaf0',
    appId: '1:511465971647:ios:bc6aa6e765335c836c0b0a',
    messagingSenderId: '511465971647',
    projectId: 'solara-29b37',
    storageBucket: 'solara-29b37.firebasestorage.app',
    iosBundleId: 'com.example.solara',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAIptkDEBQBSgyOBkeVoMe2TxR62cnLv0Y',
    appId: '1:511465971647:web:985e35382a5890ca6c0b0a',
    messagingSenderId: '511465971647',
    projectId: 'solara-29b37',
    authDomain: 'solara-29b37.firebaseapp.com',
    storageBucket: 'solara-29b37.firebasestorage.app',
    measurementId: 'G-YSFLTW9F76',
  );
}
